global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "spring-actuator"
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["config-server:8888", "eureka-server:8761"]
#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "<Your Grafana Username>"
#      password: "<Your Grafana API key>"
