server:
  port: 7788


spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:4436/notification_db
    username: useradmin
    password: useradmsecret

  jpa:
    hibernate:
      ddl-auto: update
      dialect=org:
        hibernate:
          dialect:
            PostgreSQL9Dialect:show-sql: true