spring:
  profiles:
    active: default,dev
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/Tekky0001/orderup-tower-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          search-paths:
            - user-service
            - keycloak-client
            - api-gateway
            - eureka-server
            - file-service
            - mail-service
            - notification-service
            - food-service
            - order-service
          default-label: main
          ignore-local-ssh-settings: true
  application:
    name: config-server

encrypt:
  key: ${ENCRYPTION_KEY}

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"