server:
  port: 7070
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  profiles:
    active: default,dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      import-check.enabled: false
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:4434/user_db
    username: useradmin
    password: useradmsecret
  security:
    oauth2:
      resourceserver:
        jwt:

          issuer-uri: https://tos.orderup.homes/auth/realms/orderup-tower
          jwk-set-uri: https://tos.orderup.homes/auth/realms/orderup-tower/protocol/openid-connect/certs
logging:
  level:
    org.springframework.security: debug
