version: "3.3"

networks:
  default:
    name: orderup
    external: true

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name:   rabbitmq
    ports:
      - "5672:5672"
      - "15671:15671"

  zipkin-server:
    image: openzipkin/zipkin:2.23
    container_name: zipkin-server
    restart: unless-stopped
    expose:
      - '9411'
    ports:
      - '9411:9411'
