version: "3.3"

volumes:
  user_data:

networks:
  default:
    name: orderup
    external: true

services:
  mail-service:
    build:
      context: ../mail-service
    ports:
      - "6672:8080"
    container_name: mail-service
    depends_on:
      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: default,docker
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8080"
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:8093/actuator/health | grep UP || exit 1"
      retries: 5
      interval: 10s
      timeout: 5s