eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true



spring:


  security:
    oauth2:
      resourceserver:
        jwt:
#           issuer-uri: http://localhost:8800/auth/realms/orderup-tower
#           jwk-set-uri: http://localhost:8800/auth/realms/orderup-tower/protocol/openid-connect/certs
          issuer-uri: https://tos.orderup.homes/auth/realms/orderup-tower
          jwk-set-uri: https://tos.orderup.homes/auth/realms/orderup-tower/protocol/openid-connect/certs
  zipkin:
    base-url: http://localhost:9411/